### ISSUE TITLE
Empty "id"

### ISSUE THREAD

**Issue by ivozandhuis** [antoinecourtin/VanGoghDataproject#1]
Empty id's probably lead to processing issues. In F653 these empty id's are not there and the data is processed correctly.

Example of empty id:
https://github.com/antoinecourtin/VanGoghDataproject/blob/cd5118d44655fe76c54840e1f1605949644f72c6/F134.json#L108

**Comment by LianWintermans** [comment]
And if so, this also explains why place of production, production date, artist, and technique are not displayed or included in the facets on the site. They are all part of the same production activity.

**Comment by LianWintermans** [comment]
Missing exhibitions: this may be due to empty id's as well. See for example
https://github.com/antoinecourtin/VanGoghDataproject/blob/cd5118d44655fe76c54840e1f1605949644f72c6/F134.json#L269

**Comment by antoinecourtin** [comment]
But these ids, I can't register them, they must not be generated by your platform, right?

**Comment by LianWintermans** [comment]
When an id is missing (absent) from the source data, a local (blank node) id will be generated by the platform. When an id is not absent, but empty, the data cannot be processed.
You must either replace them with a URI (which need not be resolvable), or remove the empty ids altogether.

**Comment by antoinecourtin** [comment]
Oh, I didn't understand! I thought I had to create an empty node. I deleted the empty id for the F134.json to test.

**Comment by antoinecourtin** [comment]
It's works
