### ISSUE TITLE
Exhibition timespans

### ISSUE THREAD

**Issue by LianWintermans** [antoinecourtin/VanGoghDataproject#2]
Exhibition timespans have properties `end_of_the_begin` and `begin_of_the_end` instead of `begin_of_the_begin` and `end_of_the_end`.
See for example
https://github.com/antoinecourtin/VanGoghDataproject/blob/cd5118d44655fe76c54840e1f1605949644f72c6/F134.json#L301
and
https://github.com/antoinecourtin/VanGoghDataproject/blob/cd5118d44655fe76c54840e1f1605949644f72c6/F134.json#L302

Though [valid according to Linked Art](https://linked.art/model/base/#time-span-details), they are (apparently) not implemented at VGW.

**Comment by antoinecourtin** [comment]
yes, it is corrected
